spring:
  application:
    name: my-gateway
  cloud:
    gateway: # gateway配置
      enabled: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: false
      routes:
        - id: my-consul-client
          uri: lb://my-consul-client
          predicates:
            - Path=/my-consul-client/**
        - id: my-consul-client-a
          uri: lb://my-consul-client-a
          predicates:
            - Path=/my-consul-client-a/**

    consul:
      host: 192.168.56.101
      port: 8500
      discovery:
        heartbeat:
          enabled: true
          ttl: 10s
server:
  port: 2000

logging:
  level:
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: DEBUG
